fos_rest:
  body_listener: true
  body_converter:
    enabled: true
  view:
    view_response_listener: true
  serializer:
      serialize_null: true
  format_listener:
    rules:
      - { path: '^/mobile_app_v2',  priorities: ['json'], fallback_format: json, prefer_extension: true }
      - { path: '^/', priorities: [ 'html', '*/*'], fallback_format: html, prefer_extension: true }
  disable_csrf_role:    null