fos_rest:
  body_listener: true
  body_converter:
    enabled: true
  view:
    view_response_listener: true
  serializer:
      serialize_null: true
  format_listener:
    rules:
      - { path: '^/api',  priorities: ['json'], fallback_format: json, prefer_extension: false }
      - { path: '^/', stop: true }
  zone:
    - { path: '^/api' }
  exception:
    enabled: true
    exception_controller: FourPaws\MobileApiBundle\Controller\ExceptionController::showAction
  #todo: param_fetcher_listener, service