four_paws_mobile_api:
  debug: '%kernel.debug%'
  exceptions:
    FourPaws\MobileApiBundle\Exception\InvalidTokenException:
      code: 1
      message: 'Неверный токен'
      status_code: 200
    FourPaws\MobileApiBundle\Exception\ValidationException:
      code: 3
      message: 'Пропущен обязательный параметр'
      status_code: 200
    FourPaws\UserBundle\Exception\UsernameNotFoundException:
      code: 5
      message: 'Пользователь с таким логином не найден'
      status_code: 200
    FourPaws\UserBundle\Exception\InvalidCredentialException:
      code: 6
      message: 'Пароль указан неверно'
      status_code: 200
    Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException:
      code: 9
      status_code: 200
      message: 'Пользователь не авторизован'
    FourPaws\MobileApiBundle\Exception\DeliveryAddressAddError:
      code: 20
      message: 'Ошибка при добавлении профиля доставки'
      status_code: 200
    FourPaws\MobileApiBundle\Exception\NoneMetroInCityException:
      code: 44
      message: 'Данные о станциях метро для этого города отсутствуют'
      status_code: 200
    FourPaws\Catalog\Exception\CategoryNotFoundException:
      code: 404
      message: 'Категория не найдена'
      status_code: 200
    FourPaws\MobileApiBundle\Exception\InvalidSignRequestException:
      code: 401
      status_code: 401
    FourPaws\MobileApiBundle\Exception\HackerException:
      code: 401
      status_code: 401
    FourPaws\MobileApiBundle\Exception\DeliveryAddressUpdateError:
      code: 1021
      message: 'Ошибка при обновления профиля доставки'
      status_code: 200

