services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    FourPaws\StoreBundle\:
        resource: '../../*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../{Entity,Tests}'
    store.service:
        class: FourPaws\StoreBundle\Service\StoreService
        public: true

    jms_serializer.array_or_false_handler:
        class: FourPaws\StoreBundle\Serialization\ArrayOrFalseHandler
        tags:
            - { name: jms_serializer.subscribing_handler }

    jms_serializer.bitrix_boolean_handler:
        class: FourPaws\StoreBundle\Serialization\BitrixBooleanHandler
        tags:
            - { name: jms_serializer.subscribing_handler }
