services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    FourPaws\FoodSelectionBundle\:
        resource: '../../*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../{Entity,Tests}'

    food_selection.service:
        class: FourPaws\FoodSelectionBundle\Service\FoodSelectionService
        public: true

    FourPaws\FoodSelectionBundle\AjaxController\:
        resource: '../../AjaxController'
        public: true
        tags: ['controller.service_arguments']

