imports:
  - { resource: config.yml }
  - { resource: parameters.yml }
  - { resource: services_dev.yml }


framework:
    router:
        resource: '%kernel.project_dir%/app/config/routes/routes_dev.yml'
        strict_requirements: true

web_profiler:
    toolbar: false
    intercept_redirects: false
