---

imports:
  - { resource: parameters.yml }

framework:
  esi: { enabled: true }
  translator: { fallbacks: ['%locale%'] }
  secret: '%secret%'
  default_locale: '%locale%'
  router:
    resource: '%kernel.project_dir%/app/config/routes/routes.yml'
    strict_requirements: ~
  form: ~
  csrf_protection: ~
  validation: { enable_annotations: true }
  serializer: { enable_annotations: true }
  trusted_hosts: ~
  session:
    # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
    storage_id: session.storage.php_bridge
    handler_id: ~
  fragments: ~
  http_method_override: true
  php_errors:
    log: true
  templating:
    engines: ['php', 'twig']

security:
  providers:
    bitrix:
      id: FourPaws\UserBundle\Security\BitrixUserProvider
  firewalls:
    main:
      anonymous: ~
      logout: ~
      guard:
        authenticators:
          - FourPaws\UserBundle\Security\BitrixAuthenticator

circle_rest_client:
  curl:
    defaults:
      CURLOPT_HTTPHEADER: ['Content-Type: application/json']
      CURLOPT_FAILONERROR: true
      CURLOPT_FORBID_REUSE: true
      CURLOPT_FRESH_CONNECT: true
      CURLOPT_USERPWD: old4lapy:8J7tQHPpN9

fos_rest:
  body_listener: true
  body_converter:
    enabled: true
  view:
    view_response_listener: true
  serializer:
      serialize_null: true
  format_listener:
    rules:
      - { path: '^/mobile_app_v2',  priorities: ['json'], fallback_format: json, prefer_extension: true }
      - { path: '^/', priorities: [ 'html', '*/*'], fallback_format: html, prefer_extension: true }
  disable_csrf_role:    null

nelmio_api_doc:
  models: { use_jms: true }
  routes:
    path_patterns:
      - ^/mobile_app_v2
  documentation:
    info:
      title: 4lapy
      description: 4 lapy mobile api
      version: 1.0.0

twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

old_sound_rabbit_mq:
    connections:
        default:
            host:     "%env(AMQP_HOST)%"
            port:     "%env(AMQP_PORT)%"
            user:     "%env(AMQP_USER)%"
            password: "%env(AMQP_PASSWORD)%"
            vhost:    '%env(AMQP_VHOST)%'
            lazy:     true
            connection_timeout: 3
            read_write_timeout: 3
            keepalive: false
            heartbeat: 0
            #Использование сокета быстрее, но он не работает из-за бага "Error reading data. Received 0 instead of expected 7 bytes"
            #See https://github.com/php-amqplib/php-amqplib/issues/72
            #See https://github.com/php-amqplib/RabbitMqBundle/issues/447
            use_socket: false

    producers:
      callback_set:
        connection:       default
        exchange_options: { name: "callback_set", type: direct }

      catalog_sync:
        connection: default
        exchange_options: {name: "catalog_sync", type: "direct"}

    consumers:
      callback_set:
        connection:       default
        exchange_options: { name: "callback_set", type: direct}
        queue_options:    { name: "callback_set" }
        callback:         callback_set.consumer

      catalog_sync:
        connection: default
        exchange_options: {name: "catalog_sync", type: "direct"}
        queue_options: {name: "catalog_sync"}
        callback: search.sync_consumer

jms_serializer:
  property_naming:
    id: jms_serialized_name_annotation_strategy
    enable_cache: true

sensio_framework_extra:
  request:
    converters: true
    auto_convert: true
    disable: ['doctrine.orm']

four_paws_sap:
  directory_sources:
    product_info:
      entity: FourPaws\SapBundle\Dto\In\Offers\Materials
      in: '%sap.product.directory.in%'
      out: '%sap.product.directory.out%'
      error: '%sap.product.directory.error%'
      filemask: 'Mat_*'
    price:
      entity: FourPaws\SapBundle\Dto\In\Prices\Prices
      in: '%sap.prices.directory.in%'
      out: '%sap.prices.directory.out%'
      error: '%sap.prices.directory.error%'
      filemask: 'Prc_*'
    stock_quantity:
      entity: FourPaws\SapBundle\Dto\In\DcStock\DcStock
      in: '%sap.stock.directory.in%'
      out: '%sap.stock.directory.out%'
      error: '%sap.stock.directory.error%'
      filemask: 'Stc_*'
    order_status:
      entity: FourPaws\SapBundle\Dto\In\Orders\Order
      in: '%sap.order.status.directory.in%'
      out: '%sap.order.status.directory.out%'
      error: '%sap.order.status.directory.error%'
      filemask: 'OrdersIM_*'
    payment_order:
      entity: FourPaws\SapBundle\Dto\In\ConfirmPayment\Order
      in: '%sap.payment.directory.in%'
      out: '%sap.payment.directory.out%'
      error: '%sap.payment.directory.error%'
      filemask: 'DP_*'
    schedule:
      entity: FourPaws\SapBundle\Dto\In\DeliverySchedule\DeliverySchedule
      in: '%sap.schedule.directory.in%'
      out: '%sap.schedule.directory.out%'
      error: '%sap.schedule.directory.error%'
      filemask: 'Sched_*'
    shop_quantity:
      entity: FourPaws\SapBundle\Dto\In\StoresStock\StoresStock
      in: '%sap.shop.directory.in%'
      out: '%sap.shop.directory.out%'
      error: '%sap.shop.directory.error%'
      filemask: 'sapbi_balance_*'
      filetype: 'csv'

  pipelines:
    catalog:
      - FourPaws\SapBundle\Dto\In\Offers\Materials
      - FourPaws\SapBundle\Dto\In\Prices\Prices
      - FourPaws\SapBundle\Dto\In\DcStock\DcStock
      - FourPaws\SapBundle\Dto\In\StoresStock\StoresStock
    order_status:
      - FourPaws\SapBundle\Consumer\OrderStatusConsumer
    delivery_schedule:
      - FourPaws\SapBundle\Consumer\DeliveryScheduleConsumer

cocur_slugify:
    lowercase: true
    separator: '_'
    rulesets: [default, russian]
