---

imports:
  - { resource: parameters.yml }
  - { resource: security.yml }
  - { resource: configs/fos_rest.yml }
  - { resource: configs/old_sound_rabbit_mq.yml }
  - { resource: configs/four_paws_sap.yml }
  - { resource: configs/four_paws_mobile_api.yml }
  - { resource: configs/env.parameters.yml }
  - { resource: configs/jms_serializer.yml }

parameters:
  manzana.guzzle.curl:
    !php/const:CURLOPT_CONNECTTIMEOUT: '%manzana.guzzle.curl.timeout%'
  recaptcha.guzzle.curl:
    !php/const:CURLOPT_CONNECTTIMEOUT: '%recaptcha.guzzle.curl.timeout%'
  callback.guzzle.curl:
    !php/const:CURLOPT_CONNECTTIMEOUT: '%callback.guzzle.curl.timeout%'

  callback:
    baseUri: '%env(CALLBACK_URI)%'
    login: '%env(CALLBACK_LOGIN)%'
    pass: '%env(CALLBACK_PASS)%'

  recaptcha:
    key: '%env(RECAPTCHA_KEY)%'
    secretKey: '%env(RECAPTCHA_SECRET_KEY)%'
    serviceUri: '%env(RECAPTCHA_URI)%'

  manzana:
    login: '%env(MANZANA_LOGIN)%'
    password: '%env(MANZANA_PASSWORD)%'
    wdsl: '%env(MANZANA_HOST)%'
    pos: kuvi_pos
    business_unit: kuvi_shop
  manzana.wdsl: '%env(MANZANA_HOST)%'
  manzana.pos.wdsl: '%env(MANZANA_HOST_POS)%'

  sms:
    login: '%env(SMS_LOGIN)%'
    password: '%env(SMS_PASSWORD)%'
    login.immediate: '%env(SMS_LOGIN_IMMEDIATE)%'
    password.immediate: '%env(SMS_PASSWORD_IMMEDIATE)%'
    start_messaging: '%sms.start_messaging%'
    stop_messaging: '%sms.stop_messaging%'
    originator: '%sms.originator%'

framework:
  esi: { enabled: true }
  translator: { fallbacks: ['%locale%'] }
  secret: '%secret%'
  default_locale: '%locale%'
  router:
    resource: '%kernel.project_dir%/app/config/routes/routes.yml'
    strict_requirements: ~
  form: ~
  csrf_protection: ~
  validation: { enable_annotations: true }
  serializer: { enable_annotations: true }
  trusted_hosts: ~
  session:
    # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
    storage_id: session.storage.php_bridge
    handler_id: FourPaws\AppBundle\Session\BitrixSessionBridge
  fragments: ~
  http_method_override: true
  php_errors:
    log: true
  templating:
    engines: ['php', 'twig']

circle_rest_client:
  curl:
    defaults:
      CURLOPT_HTTPHEADER: ['Content-Type: application/json']
      CURLOPT_FAILONERROR: true
      CURLOPT_FORBID_REUSE: true
      CURLOPT_FRESH_CONNECT: true
      CURLOPT_USERPWD: old4lapy:8J7tQHPpN9


nelmio_api_doc:
  models: { use_jms: true }
  routes:
    path_patterns:
      - ^/mobile_app_v2
  documentation:
    info:
      title: 4lapy
      description: 4 lapy mobile api
      version: 1.0.0

twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

sensio_framework_extra:
  request:
    converters: true
    auto_convert: true
    disable: ['doctrine.orm']

cocur_slugify:
    lowercase: true
    separator: '_'
    rulesets: [default, russian]
