imports:
  - { resource: parameters.yml }
  - { resource: config_dev.yml }
  - { resource: services_test.yml }

services:
    FourPaws\MobileApiBundle\Services\Security\TokenGeneratorInterface:
        class: FourPaws\MobileApiBundle\Services\Security\FakeTokenGenerator

    FourPaws\MobileApiBundle\Services\CaptchaServiceInterface:
        class: FourPaws\MobileApiBundle\Services\FakeCaptchaService
