imports:
  - { resource: config_dev.yml }

framework:
  test: ~

services:
    FourPaws\MobileApiBundle\Services\Security\TokenGeneratorInterface:
        class: FourPaws\MobileApiBundle\Services\Security\FakeTokenGenerator