---

parameters:
  locale: ru
  secret: 7371018148815e9de0f88dba6a44126524d6a80e

  migrator:
    token: c81789b482ecbe6976f496a9697d75de

  sms:
    start_messaging: '09:00'
    stop_messaging: '21:00'
    login: "%env(SMS_LOGIN)%"
    password: "%env(SMS_PASSWORD)%"
    originator: 4lapy

  expertsender:
    url: https://api.esv2.com
    key: ivaacmVjzakOzRLeYjKy

  # See \Elastica\Client::$_config for more options
  elastica.client_options:
    - timeout: 60
      # ВНИМАНИЕ! Логирование следует включать только временно при отладке,
      # т.к. оно записывает очень много данных в лог.
    - log: false
    - bigintConversion: false
    - retryOnConflict: 0
