---

parameters:
  locale: ru
  secret: 7371018148815e9de0f88dba6a44126524d6a80e

  manzana:
    login: '%env(MANZANA_LOGIN)%'
    password: '%env(MANZANA_PASSWORD)%'
    wdsl: '%env(MANZANA_HOST)%'
  manzana_pos:
    pos: ishop2
    business_unit: ishop
    organization: 1
    organization_name: fourfoots

  manzana.wdsl: '%env(MANZANA_HOST)%'
  manzana.pos.wdsl: '%env(MANZANA_HOST_POS)%'
  manzana.guzzle.curl:
    !php/const:CURLOPT_CONNECTTIMEOUT: 3

  migrator:
    token: c81789b482ecbe6976f496a9697d75de

  sms:
    start_messaging: '09:00'
    stop_messaging: '21:00'
    login: '%env(SMS_LOGIN)%'
    password: '%env(SMS_PASSWORD)%'
    originator: 4lapy

  expertsender:
    url: https://api.esv2.com
    key: ivaacmVjzakOzRLeYjKy

  recaptcha:
    key: '%env(RECAPTCHA_KEY)%'
    secretKey: '%env(RECAPTCHA_SECRET_KEY)%'
    serviceUri: 'https://www.google.com/recaptcha/api/siteverify'

  recaptcha.guzzle.curl:
    !php/const:CURLOPT_CONNECTTIMEOUT: 3

  callback:
    baseUri: 'https://4584.vats-on.ru'
    login: '%env(CALLBACK_LOGIN)%'
    pass: '%env(CALLBACK_PASS)%'

  callback.guzzle.curl:
    !php/const:CURLOPT_CONNECTTIMEOUT: 3

  # See \Elastica\Client::$_config for more options
  elastica.client_options:
    - timeout: 60
      # ВНИМАНИЕ! Логирование следует включать только временно при отладке,
      # т.к. оно записывает очень много данных в лог.
    - log: false
    - bigintConversion: false
    - retryOnConflict: 0

  # Sap directories
  sap.product.directory.in: '%sap.directory%'
  sap.product.directory.out: '%sap.directory%/ArchMat/'
  sap.product.directory.error: '%sap.directory%/ArchMat_Errors/'

  sap.prices.directory.in: '%sap.directory%'
  sap.prices.directory.out: '%sap.directory%/ArchPrice/'
  sap.prices.directory.error: '%sap.directory%/ArchPrice_Errors/'

  sap.stock.directory.in: '%sap.directory%'
  sap.stock.directory.out: '%sap.directory%/ArchStock/'
  sap.stock.directory.error: '%sap.directory%/ArchStock_Errors/'

  sap.order.directory.out: '%sap.directory%'

  sap.order.status.directory.in: '%sap.directory%'
  sap.order.status.directory.out: '%sap.directory%/ArchZakaz/'
  sap.order.status.directory.error: '%sap.directory%/ArchZakaz_Errors/'

  sap.payment.directory.in: '%sap.directory%'
  sap.payment.directory.out: '%sap.directory%/ArchZakazOplata/'
  sap.payment.directory.error: '%sap.directory%/ArchZakazOplata_Errors/'

  sap.payment.confirmation.directory.out: '%sap.directory%'

  sap.schedule.directory.in: '%sap.directory%'
  sap.schedule.directory.out: '%sap.directory%/ArchSchedule/'
  sap.schedule.directory.error: '%sap.directory%/ArchSchedule_Errors/'

  sap.shop.directory.in: '%sap.directory%/SAPBW/'
  sap.shop.directory.out: '%sap.directory%/SAPBW/'
  sap.shop.directory.error: '%sap.directory%/SAPBW_Errors/'
