parameters:
  manzana:
    login: admin
    password: Cp46hwUm
    pos_wdsl: http://37.230.152.90:8083/POSProcessing.asmx?WSDL
    wdsl: http://37.230.152.90:8182/PrivateOfficeDataService.asmx?WSDL
    pos: kuvi_pos
    business_unit: kuvi_shop

imports:
  - { resource: config.yml }
  - { resource: services_prod.yml }

old_sound_rabbit_mq:
    connections:
        default:
            host:     "%env(AMQP_HOST)%"
            port:     "%env(AMQP_PORT)%"
            user:     "%env(AMQP_USER)%"
            password: "%env(AMQP_PASSWORD)%"
            vhost:    '/'
            lazy:     false
            connection_timeout: 3
            read_write_timeout: 3
            keepalive: false
            heartbeat: 0
            use_socket: true
    # example of the producers and consumers
    #  producers:
    #   upload_picture:
    #       connection:       default
    #       exchange_options: {name: 'upload-picture', type: direct}
    #       service_alias:    my_app_service # no alias by default
    #  consumers:
    #   upload_picture:
    #       connection:       default
    #       exchange_options: {name: 'upload-picture', type: direct}
    #       queue_options:    {name: 'upload-picture'}
    #       callback:         upload_picture_service

