---

parameters:
  locale: ru
  secret: 7371018148815e9de0f88dba6a44126524d6a80e

  migrator:
    token: c81789b482ecbe6976f496a9697d75de

  sms:
    login: 4lapy
    password: hoxiqaney
    originator: 4lapy

  expertsender:
    url: https://api.esv2.com
    key: ivaacmVjzakOzRLeYjKy

  # See \Elastica\Client::$_config for more options
  elastica.client_options:
    - timeout: 60
    - log: false
    - bigintConversion: false
    - retryOnConflict: 0
