---

parameters:
  locale: ru
  secret: 7371018148815e9de0f88dba6a44126524d6a80e

  migrator:
    CURLOPT_FAILONERROR: true
    CURLOPT_FORBID_REUSE: true
    CURLOPT_FRESH_CONNECT: true
    CURLOPT_USERPWD: old4lapy:8J7tQHPpN9