---

services:
  bitrix.ciblockelement:
    class: CIBlockElement

  bitrix.ccatalogproduct:
    class: CCatalogProduct

  bitrix.event.manager:
    class: Bitrix\Main\EventManager
    factory: ['Bitrix\Main\EventManager', getInstance]

  bitrix.context:
      class: Bitrix\Main\Context
      factory: ['Bitrix\Main\Context', getCurrent]
      shared: false

  bitrix.cuser:
      class: CUser

  bitrix.cmain:
      class: CMain