---

imports:
  - { resource: services/bitrix-hl-blocks.yml }

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  catalog.service:
    class: FourPaws\Catalog\CatalogService
    arguments: ['@bx.hlblock.filter', '@jms_serializer']

  search.factory:
    class: FourPaws\Search\Factory

  elastica.client:
    class: Elastica\Client
    factory: 'search.factory:createElasticaClient'
    arguments: ['%elastica.client_options%']

  search.sync_consumer:
    class: FourPaws\Search\Consumer\CatalogSyncConsumer
    arguments: ['@jms_serializer']

  search.service:
    class: FourPaws\Search\SearchService

  user.service:
    class: FourPaws\User\UserService

  health.service:
    class: FourPaws\Health\HealthService

  sms.service:
    class: FourPaws\External\SmsService

  manzana.service:
    class: FourPaws\External\ManzanaService

  expertender.service:
    class: FourPaws\External\ExpertsenderService

  product.autosort.service:
    class: FourPaws\ProductAutoSort\ProductAutoSortService

  jms_identical_naming_strategy:
    class: JMS\Serializer\Naming\IdenticalPropertyNamingStrategy
