---

imports:
  - { resource: services/bitrix-hl-blocks.yml }

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  catalog.service:
    class: FourPaws\Catalog\CatalogService
    arguments: ['@bx.hlblock.filter']

  user.service:
    class: FourPaws\User\UserService

  health.service:
    class: FourPaws\Health\HealthService
