---

imports:
  - { resource: services/bitrix-hl-blocks.yml }

services:

  catalog.service:
    class: FourPaws\Catalog\CatalogService
    arguments: ['@bx.hlblock.filter']

  user.service:
    class: FourPaws\User\UserService

  product.autosort.service:
    class: FourPaws\ProductAutoSort\ProductAutoSortService
