<?
$aMenuLinks = [
    [
        'Мои заказы',
        '/personal/orders/',
        [],
        ['icon' => 'icon-order'],
        "\$USER->IsAuthorized()",
    ],
    [
        'Адреса доставки',
        '/personal/address/',
        [],
        ['icon' => 'icon-delivery-header'],
        "\$USER->IsAuthorized()",
    ],
    [
        'Подписка на доставку',
        '/personal/subscribe/',
        [],
        ['icon' => 'icon-delivery-menu'],
        "\$USER->IsAuthorized()",
    ],
    [
        'Мои питомцы',
        '/personal/pets/',
        [],
        ['icon' => 'icon-pet'],
        "\$USER->IsAuthorized()",
    ],
    [
        'Бонусы',
        '/personal/bonus/',
        [],
        ['icon' => 'icon-bonus'],
        "\$USER->IsAuthorized()",
    ],
    [
        'Реферальная программа',
        '/personal/referral/',
        [],
        ['icon' => 'icon-menu-referal'],
        "\$USER->IsAuthorized() && \\in_array(30, \$USER->GetUserGroupArray())",
    ],
    [
        'Профиль',
        '/personal/',
        [],
        ['icon' => 'icon-profile'],
        "\$USER->IsAuthorized()",
    ],
    [
        'Топ 10 товаров',
        '/personal/top/',
        [],
        ['icon' => 'icon-empty-star'],
        "\$USER->IsAuthorized()",
    ],
    [
        'Выход',
        '?logout=yes',
        [],
        ['icon' => 'icon-exit'],
        "\$USER->IsAuthorized() && !\FourPaws\App\Application::getInstance()->getContainer()->get(\FourPaws\UserBundle\Service\CurrentUserProviderInterface::class)->isAvatarAuthorized()",
    ],
    [
        'Вернуться',
        '/front-office/avatar/logout.php',
        [],
        ['icon' => 'icon-exit'],
        "\FourPaws\App\Application::getInstance()->getContainer()->get(\FourPaws\UserBundle\Service\CurrentUserProviderInterface::class)->isAvatarAuthorized()",
    ],
];
